// ── Optional confluences (2026-09-14 study) ──────────────────────────────────
// One list per params block. Each key is a backend dataclass field; `kind` is
// 'bool', 'num' or an options array. Defaults reproduce the engines as they were.
export const CONFLUENCE_FIELDS = {
  synth: [
    ['side', 'Side', ['both', 'long', 'short']],
    ['require_trend_with', 'EMA regime with the trade', 'bool'],
    ['require_htf_trend', 'With the H1 trend (600-bar EMA)', 'bool'],
    ['adx_filter', 'ADX(14) filter', ['OFF', 'TREND', 'RANGE']],
    ['require_vol_high', 'Volatility above its daily median', 'bool'],
    ['require_candle_confirm', 'Signal candle closes the trade\'s way', 'bool'],
    ['require_strong_close', 'Signal candle closes in its outer 30%', 'bool'],
    ['time_filter', 'Time window', ['ALL', 'LONDON', 'NEWYORK']],
    ['max_hold_bars', 'Close after N M5 bars (0 = off, study: 288)', 'num'],
  ],
  htf_fvg_flip: [
    ['htf_trend_filter', 'HTF structure trend', ['COUNTER', 'WITH', 'OFF']],
    ['require_retest', 'Wait for the M5 gap retest', 'bool'],
    ['fvg_displacement_atr_mult', 'HTF gap displacement (× ATR, 0 = off)', 'num'],
    ['fvg_displacement_body_pct', 'HTF gap body share (0 = off)', 'num'],
    ['require_first_tap', 'First tap only (when re-taps allowed)', 'bool'],
    ['min_inversion_disp_atr', 'Min inversion close beyond gap (× ATR)', 'num'],
    ['require_stop_ok', 'Skip floored stops', 'bool'],
    ['require_htf_trend', 'With the H1 trend (600-bar EMA)', 'bool'],
    ['require_adx_trend', 'ADX(14) >= 20', 'bool'],
    ['require_vol_high', 'Volatility above its daily median', 'bool'],
    ['time_filter', 'Trigger window', ['ALL', 'RTH', 'LONDON', 'NEWYORK']],
    ['side', 'Side', ['both', 'long', 'short']],
    ['max_hold_bars', 'Close after N M5 bars (0 = off, study: 288)', 'num'],
  ],
  bias_ifvg: [
    ['bias_mode', 'Bias source', ['H4', 'OFF']],
    ['key_levels', 'Key levels', ['ALL', 'FVG', 'CISD_REJ']],
    ['ifvg_leg_mode', 'IFVG leg', ['APPROACH', 'REACTION', 'BOTH']],
    ['session_filter_enabled', 'Session window on', 'bool'],
    ['day_stop_enabled', 'Day-stop rule', 'bool'],
    ['min_confluent_levels', 'Min overlapping key levels', 'num'],
    ['require_h4_aligned', 'H4 FVG points the trade\'s way', 'bool'],
    ['min_inversion_disp_atr', 'Min inversion close beyond gap (× ATR)', 'num'],
    ['require_stop_ok', 'Skip floored stops', 'bool'],
    ['require_htf_trend', 'With the H1 trend (600-bar EMA)', 'bool'],
    ['require_adx_trend', 'ADX(14) >= 20', 'bool'],
    ['require_vol_high', 'Volatility above its daily median', 'bool'],
    ['time_filter', 'Trigger window', ['ALL', 'NY_OPEN', 'LONDON', 'NEWYORK']],
    ['side', 'Side', ['both', 'long', 'short']],
    ['max_hold_bars', 'Close after N M5 bars (0 = off, study: 288)', 'num'],
  ],
};

export const CONFLUENCE_DEFAULTS = {
  synth: { side: 'both', require_trend_with: false, require_htf_trend: false, adx_filter: 'OFF',
    require_vol_high: false, require_candle_confirm: false, require_strong_close: false, time_filter: 'ALL',
    max_hold_bars: 0 },
  htf_fvg_flip: { htf_trend_filter: 'COUNTER', require_retest: true, fvg_displacement_atr_mult: 1.5,
    fvg_displacement_body_pct: 0.6, require_first_tap: false, min_inversion_disp_atr: 0, require_stop_ok: false,
    require_htf_trend: false, require_adx_trend: false, require_vol_high: false, time_filter: 'ALL', side: 'both',
    max_hold_bars: 0 },
  bias_ifvg: { bias_mode: 'H4', key_levels: 'ALL', ifvg_leg_mode: 'APPROACH', session_filter_enabled: true,
    day_stop_enabled: true, min_confluent_levels: 0, require_h4_aligned: false, min_inversion_disp_atr: 0,
    require_stop_ok: false, require_htf_trend: false, require_adx_trend: false, require_vol_high: false,
    time_filter: 'ALL', side: 'both', max_hold_bars: 0 },
};
